name: Update Key File

on:
  push:
    branches:
      - main

# Set permissions to allow pushing changes
permissions:
  contents: write

jobs:
  update_key:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository with token to ensure push permissions
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # Replace content in Youre_Key.txt
      - name: Replace content in Youre_Key.txt
        run: echo "PulseKey_" > Youre_Key.txt

      # Commit changes if the file has changed
      - name: Commit changes if file has changed
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "actions@github.com"
          
          # Check if Youre_Key.txt has changes
          if ! git diff --exit-code Youre_Key.txt; then
            git add Youre_Key.txt
            git commit -m "Update Youre_Key.txt with PulseKey_"
            git push
          else
            echo "No changes detected in Youre_Key.txt, skipping commit."
          fi
