name: Update Key File

on:
  push:
    branches:
      - main

jobs:
  update_key:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Replace content in Youre_Key.txt
        run: echo "PulseKey_" > Youre_Key.txt

      - name: Commit changes if file has changed
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "actions@github.com"
          if ! git diff --exit-code Youre_Key.txt; then
            git add Youre_Key.txt
            git commit -m "Update Youre_Key.txt with PulseKey_"
            git push
          else
            echo "No changes detected in Youre_Key.txt, skipping commit."
          fi
