name: Update Key

on:
  push:
    branches:
      - main

jobs:
  update_key:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Generate Random Key
      id: generate_key
      run: |
        # Generate a random key
        KEY="PulseKey_$(tr -dc 'A-Za-z0-9' < /dev/urandom | head -c 30)"
        echo "Generated key: $KEY"
        echo "::set-output name=key::$KEY"

    - name: Clear and Update Youre_Key.txt
      run: |
        # Clear the file and write the new key
        echo "" > Youre_Key.txt  # Clear the file
        echo "${{ steps.generate_key.outputs.key }}" > Youre_Key.txt  # Write new key

    - name: Commit Changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add Youre_Key.txt
        git commit -m "Update Youre_Key.txt with a new key" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Verwende den standardmäßigen GitHub-Token
